# -*- coding: utf-8 -*-
"""college student database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoJAzQYLvf5Ar6LAk4XdGZ0hU0dz3MxF
"""

def add_student(student_dict, roll_no, name, branch, cgpa, city):
    if roll_no not in student_dict:
        student_dict[roll_no] = {'Name': name, 'Branch': branch, 'CGPA': cgpa, 'City': city}
        print("New student successfully added!")
    else:
        print("Error: Roll number already exists.")


def remove_student(student_dict, roll_no):
    if roll_no in student_dict:
        del student_dict[roll_no]
        print("Student has been successfully removed.")
    else:
        print("Error: Roll number not found.")


def update_student(student_dict, roll_no, name=None, branch=None, cgpa=None, city=None):
    if roll_no in student_dict:
        if name:
            student_dict[roll_no]['Name'] = name
        if branch:
            student_dict[roll_no]['Branch'] = branch
        if cgpa is not None:
            student_dict[roll_no]['CGPA'] = cgpa
        if city:
            student_dict[roll_no]['City'] = city
        print("Student details updated successfully.")
    else:
        print("Error: Roll number not found.")


def list_students(student_dict):
    print("\n\n College Student Database \n")
    if not student_dict:
        print("Currently, there are no students to show.")
    for roll_no, details in student_dict.items():
        print(f"Roll No: {roll_no}, Name: {details['Name']}, Branch: {details['Branch']}, CGPA: {details['CGPA']}, City: {details['City']}")


# Main function
if __name__ == "__main__":
    students = {}

    while True:
        print(
            "\n==================================== College Student Database ============================================\n\n")
        print("Press 1: To List Students")
        print("Press 2: To Add Student")
        print("Press 3: To Remove Student")
        print("Press 4: To Update Student")
        print("Press 5: To Exit")

        choice = int(input("\nEnter your choice (1, 2, 3, 4, 5): "))

        if choice == 2:
            roll_no = int(input("Enter roll number: "))
            name = input("Enter student name: ")
            branch = input("Enter student branch: ")
            cgpa = float(input("Enter student CGPA (out of 10.0): "))
            city = input("Enter student city: ")
            add_student(students, roll_no, name, branch, cgpa, city)

        elif choice == 3:
            roll_no = int(input("Enter roll number: "))
            remove_student(students, roll_no)

        elif choice == 4:
            roll_no = int(input("Enter roll number: "))
            name = input("Enter new student name (leave blank to keep current): ")
            branch = input("Enter new student branch (leave blank to keep current): ")
            cgpa = input("Enter new student CGPA (leave blank to keep current): ")
            city = input("Enter new student city (leave blank to keep current): ")
            update_student(students, roll_no, name if name else None, branch if branch else None, float(cgpa) if cgpa else None, city if city else None)

        elif choice == 1:
            list_students(students)

        elif choice == 5:
            print("Exit from the database")
            break

        else:
            print("Invalid selection! Please choose a valid option.")

